import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import XpertServices from "./components/homepage/XpertServices";
import Footer from "./components/footer/Footer";
import Slideshow from './components/Slideshow/Slideshow';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
    
      <XpertServices />
      {children}
      <Slideshow />
      <Footer />
       </body>
    </html>
  );
}
