
// layout.js
import { Inter } from "next/font/google";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";
import Script from 'next/script'; // Import Script from next/script
// Import Bootstrap CSS directly in layout.js
import 'bootstrap/dist/css/bootstrap.min.css';

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "DhanXpert",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Navbar />
       
        

        {children}

        
        <Footer />
        {/* Add Script tag for Bootstrap JavaScript */}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
